algoritmo "teste enquanto"
//primeiro programa usando "ENQUANTO"
// O PROGRAMA SOMA TODOS OS VALORES QUE LER, E PARA QUANDO LÊ O NUMERO 0

var

x, soma : inteiro

inicio

escreva("Digite o primeiro número : ")
leia(x)

soma <- 0

//se a condição for verdadeira ele executa e volta
enquanto (x <> 0) faca
    soma <- soma + x
    escreva("Digite outro numero: ")
        leia(x) 
fimenquanto

escreval("SOMA = ", soma)

fimalgoritmo